"""initial_schema

Revision ID: 6f6fe7cd3741
Revises: 
Create Date: 2026-03-18 15:39:20.214616
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6f6fe7cd3741'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('assignments', 'request_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('assignments', 'tutor_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('assignments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               nullable=False,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16820_ix_assignments_request_id', table_name='assignments')
    op.drop_index('idx_16820_ix_assignments_status', table_name='assignments')
    op.drop_index('idx_16820_ix_assignments_tutor_user_id', table_name='assignments')
    op.drop_index('idx_16820_sqlite_autoindex_assignments_1', table_name='assignments')
    op.create_index(op.f('ix_assignments_request_id'), 'assignments', ['request_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_tutor_user_id'), 'assignments', ['tutor_user_id'], unique=False)
    op.create_unique_constraint('uq_assignment_request', 'assignments', ['request_id'])
    op.alter_column('auth_identities', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('auth_identities', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('auth_identities', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('auth_identities', 'provider_user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('auth_identities', 'email_normalized',
               existing_type=sa.TEXT(),
               type_=sa.String(length=320),
               existing_nullable=True)
    op.alter_column('auth_identities', 'is_verified',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('auth_identities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16779_ix_auth_identities_provider', table_name='auth_identities')
    op.drop_index('idx_16779_ix_auth_identities_user_id', table_name='auth_identities')
    op.drop_index('idx_16779_sqlite_autoindex_auth_identities_1', table_name='auth_identities')
    op.drop_index('idx_16779_sqlite_autoindex_auth_identities_2', table_name='auth_identities')
    op.create_index('ix_auth_identities_provider', 'auth_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_unique_constraint('uq_auth_identity_email', 'auth_identities', ['email_normalized'])
    op.create_unique_constraint('uq_auth_identity_provider_user', 'auth_identities', ['provider', 'provider_user_id'])
    op.add_column('email_login_codes', sa.Column('email_normalized', sa.String(length=255), nullable=True))
    op.add_column('email_login_codes', sa.Column('code_hash', sa.String(length=128), nullable=False))
    op.alter_column('email_login_codes', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('email_login_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('email_login_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('email_login_codes', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_email_login_codes_email_normalized'), 'email_login_codes', ['email_normalized'], unique=False)
    op.drop_column('email_login_codes', 'email')
    op.drop_column('email_login_codes', 'code')
    op.alter_column('messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('messages', 'sender_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('messages', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_16803_ix_messages_created_at', table_name='messages')
    op.drop_index('idx_16803_ix_messages_sender_user_id', table_name='messages')
    op.drop_index('idx_16803_ix_messages_thread_id', table_name='messages')
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'entity_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('notifications', 'telegram_sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16836_ix_notifications_created_at', table_name='notifications')
    op.drop_index('idx_16836_ix_notifications_is_read', table_name='notifications')
    op.drop_index('idx_16836_ix_notifications_user_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('offers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('offers', 'request_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('offers', 'to_tutor_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('offers', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('offers', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               nullable=False,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16827_ix_offers_request_id', table_name='offers')
    op.drop_index('idx_16827_ix_offers_status', table_name='offers')
    op.drop_index('idx_16827_ix_offers_to_tutor_user_id', table_name='offers')
    op.drop_index('idx_16827_sqlite_autoindex_offers_1', table_name='offers')
    op.create_index(op.f('ix_offers_request_id'), 'offers', ['request_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_to_tutor_user_id'), 'offers', ['to_tutor_user_id'], unique=False)
    op.create_unique_constraint('uq_offer_request_tutor', 'offers', ['request_id', 'to_tutor_user_id'])
    op.alter_column('requests', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('requests_id_seq'::regclass)"))
    op.alter_column('requests', 'author_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('requests', 'request_kind',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('requests', 'subject',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('requests', 'level',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('requests', 'format',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('requests', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('requests', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('requests', 'slug',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('requests', 'commission_value',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('requests', 'turbo_enabled',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('requests', 'turbo_sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('requests', 'assigned_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('requests', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('requests', 'admin_hidden',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_16789_ix_requests_author_user_id', table_name='requests')
    op.drop_index('idx_16789_ix_requests_status', table_name='requests')
    op.create_index(op.f('ix_requests_author_user_id'), 'requests', ['author_user_id'], unique=False)
    op.alter_column('responses', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('responses', 'request_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('responses', 'from_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('responses', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('responses', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16812_ix_responses_created_at', table_name='responses')
    op.drop_index('idx_16812_ix_responses_from_user_id', table_name='responses')
    op.drop_index('idx_16812_ix_responses_request_id', table_name='responses')
    op.create_index(op.f('ix_responses_from_user_id'), 'responses', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_responses_request_id'), 'responses', ['request_id'], unique=False)
    op.alter_column('tg_link_tokens', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tg_link_tokens', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=96),
               nullable=False)
    op.alter_column('tg_link_tokens', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('tg_link_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('tg_link_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('tg_link_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_16866_sqlite_autoindex_tg_link_tokens_1', table_name='tg_link_tokens')
    op.create_index(op.f('ix_tg_link_tokens_token'), 'tg_link_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_tg_link_tokens_user_id'), 'tg_link_tokens', ['user_id'], unique=False)
    op.alter_column('threads', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('threads', 'request_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('threads', 'author_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('threads', 'tutor_user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16846_ix_threads_author_user_id', table_name='threads')
    op.drop_index('idx_16846_ix_threads_request_id', table_name='threads')
    op.drop_index('idx_16846_ix_threads_tutor_user_id', table_name='threads')
    op.drop_index('idx_16846_sqlite_autoindex_threads_1', table_name='threads')
    op.create_index(op.f('ix_threads_author_user_id'), 'threads', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_threads_request_id'), 'threads', ['request_id'], unique=False)
    op.create_index(op.f('ix_threads_tutor_user_id'), 'threads', ['tutor_user_id'], unique=False)
    op.create_unique_constraint('uq_thread_request', 'threads', ['request_id'])
    op.alter_column('tutor_profiles', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tutor_profiles', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('tutor_profiles', 'bumped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('tutor_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tutor_profiles', 'subjects_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('tutor_profiles', 'levels_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('tutor_profiles', 'formats_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('tutor_profiles', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'price_from',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'price_to',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'is_listed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tutor_profiles', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tutor_profiles', 'seo_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'seo_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'telegram_contact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'vk_contact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'uploaded_photo_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16852_ix_tutor_profiles_slug', table_name='tutor_profiles')
    op.drop_index('idx_16852_ix_tutor_profiles_user_id', table_name='tutor_profiles')
    op.drop_index('idx_16852_sqlite_autoindex_tutor_profiles_1', table_name='tutor_profiles')
    op.create_unique_constraint(None, 'tutor_profiles', ['user_id'])
    op.drop_constraint('tutor_profiles_user_id_fkey', 'tutor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('users', 'tg_chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'tg_notify_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_16751_sqlite_autoindex_users_1', table_name='users')
    op.drop_index('idx_16751_ux_users_email', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email')
    op.alter_column('vk_oauth_states', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('vk_oauth_states', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=96),
               nullable=False)
    op.alter_column('vk_oauth_states', 'code_verifier',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               nullable=False)
    op.alter_column('vk_oauth_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('vk_oauth_states', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('idx_16761_sqlite_autoindex_vk_oauth_states_1', table_name='vk_oauth_states')
    op.create_index(op.f('ix_vk_oauth_states_state'), 'vk_oauth_states', ['state'], unique=True)
    op.drop_column('vk_oauth_states', 'device_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_oauth_states', sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vk_oauth_states_state'), table_name='vk_oauth_states')
    op.create_index('idx_16761_sqlite_autoindex_vk_oauth_states_1', 'vk_oauth_states', ['state'], unique=True)
    op.alter_column('vk_oauth_states', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('vk_oauth_states', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('vk_oauth_states', 'code_verifier',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('vk_oauth_states', 'state',
               existing_type=sa.String(length=96),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('vk_oauth_states', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('users', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('idx_16751_ux_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_16751_sqlite_autoindex_users_1', 'users', ['telegram_id'], unique=True)
    op.alter_column('users', 'tg_notify_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'tg_chat_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'photo_url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_constraint(None, 'tutor_profiles', type_='foreignkey')
    op.create_foreign_key('tutor_profiles_user_id_fkey', 'tutor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tutor_profiles', type_='unique')
    op.create_index('idx_16852_sqlite_autoindex_tutor_profiles_1', 'tutor_profiles', ['user_id'], unique=True)
    op.create_index('idx_16852_ix_tutor_profiles_user_id', 'tutor_profiles', ['user_id'], unique=True)
    op.create_index('idx_16852_ix_tutor_profiles_slug', 'tutor_profiles', ['slug'], unique=False)
    op.alter_column('tutor_profiles', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tutor_profiles', 'uploaded_photo_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'vk_contact',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'telegram_contact',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'seo_description',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'seo_title',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'slug',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tutor_profiles', 'is_listed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tutor_profiles', 'price_to',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'price_from',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'city',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'formats_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('tutor_profiles', 'levels_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('tutor_profiles', 'subjects_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('tutor_profiles', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tutor_profiles', 'display_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tutor_profiles', 'bumped_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tutor_profiles', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('tutor_profiles', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_thread_request', 'threads', type_='unique')
    op.drop_index(op.f('ix_threads_tutor_user_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_request_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_author_user_id'), table_name='threads')
    op.create_index('idx_16846_sqlite_autoindex_threads_1', 'threads', ['request_id'], unique=True)
    op.create_index('idx_16846_ix_threads_tutor_user_id', 'threads', ['tutor_user_id'], unique=False)
    op.create_index('idx_16846_ix_threads_request_id', 'threads', ['request_id'], unique=False)
    op.create_index('idx_16846_ix_threads_author_user_id', 'threads', ['author_user_id'], unique=False)
    op.alter_column('threads', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('threads', 'tutor_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('threads', 'author_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('threads', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('threads', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_tg_link_tokens_user_id'), table_name='tg_link_tokens')
    op.drop_index(op.f('ix_tg_link_tokens_token'), table_name='tg_link_tokens')
    op.create_index('idx_16866_sqlite_autoindex_tg_link_tokens_1', 'tg_link_tokens', ['token'], unique=True)
    op.alter_column('tg_link_tokens', 'used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tg_link_tokens', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tg_link_tokens', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tg_link_tokens', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('tg_link_tokens', 'token',
               existing_type=sa.String(length=96),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tg_link_tokens', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_responses_request_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_from_user_id'), table_name='responses')
    op.create_index('idx_16812_ix_responses_request_id', 'responses', ['request_id'], unique=False)
    op.create_index('idx_16812_ix_responses_from_user_id', 'responses', ['from_user_id'], unique=False)
    op.create_index('idx_16812_ix_responses_created_at', 'responses', ['created_at'], unique=False)
    op.alter_column('responses', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('responses', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('responses', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('responses', 'from_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('responses', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('responses', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_requests_author_user_id'), table_name='requests')
    op.create_index('idx_16789_ix_requests_status', 'requests', ['status'], unique=False)
    op.create_index('idx_16789_ix_requests_author_user_id', 'requests', ['author_user_id'], unique=False)
    op.alter_column('requests', 'admin_hidden',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('requests', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('requests', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('requests', 'assigned_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('requests', 'assigned_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('requests', 'turbo_sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('requests', 'turbo_enabled',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('requests', 'commission_value',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('requests', 'slug',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('requests', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('requests', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('requests', 'format',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('requests', 'level',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('requests', 'subject',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('requests', 'request_kind',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('requests', 'author_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('requests', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('requests_id_seq'::regclass)"))
    op.drop_constraint('uq_offer_request_tutor', 'offers', type_='unique')
    op.drop_index(op.f('ix_offers_to_tutor_user_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_request_id'), table_name='offers')
    op.create_index('idx_16827_sqlite_autoindex_offers_1', 'offers', ['request_id', 'to_tutor_user_id'], unique=True)
    op.create_index('idx_16827_ix_offers_to_tutor_user_id', 'offers', ['to_tutor_user_id'], unique=False)
    op.create_index('idx_16827_ix_offers_status', 'offers', ['status'], unique=False)
    op.create_index('idx_16827_ix_offers_request_id', 'offers', ['request_id'], unique=False)
    op.alter_column('offers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('offers', 'status',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('offers', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('offers', 'to_tutor_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('offers', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('offers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.create_index('idx_16836_ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_16836_ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_16836_ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('notifications', 'telegram_sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'entity_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('notifications', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.create_index('idx_16803_ix_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.create_index('idx_16803_ix_messages_sender_user_id', 'messages', ['sender_user_id'], unique=False)
    op.create_index('idx_16803_ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'read_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'sender_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('email_login_codes', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('email_login_codes', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_email_login_codes_email_normalized'), table_name='email_login_codes')
    op.alter_column('email_login_codes', 'used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('email_login_codes', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('email_login_codes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('email_login_codes', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('email_login_codes', 'code_hash')
    op.drop_column('email_login_codes', 'email_normalized')
    op.drop_constraint('uq_auth_identity_provider_user', 'auth_identities', type_='unique')
    op.drop_constraint('uq_auth_identity_email', 'auth_identities', type_='unique')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index('ix_auth_identities_provider', table_name='auth_identities')
    op.create_index('idx_16779_sqlite_autoindex_auth_identities_2', 'auth_identities', ['email_normalized'], unique=True)
    op.create_index('idx_16779_sqlite_autoindex_auth_identities_1', 'auth_identities', ['provider', 'provider_user_id'], unique=True)
    op.create_index('idx_16779_ix_auth_identities_user_id', 'auth_identities', ['user_id'], unique=False)
    op.create_index('idx_16779_ix_auth_identities_provider', 'auth_identities', ['provider'], unique=False)
    op.alter_column('auth_identities', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('auth_identities', 'is_verified',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('auth_identities', 'email_normalized',
               existing_type=sa.String(length=320),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auth_identities', 'provider_user_id',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auth_identities', 'provider',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('auth_identities', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('auth_identities', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_assignment_request', 'assignments', type_='unique')
    op.drop_index(op.f('ix_assignments_tutor_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_request_id'), table_name='assignments')
    op.create_index('idx_16820_sqlite_autoindex_assignments_1', 'assignments', ['request_id'], unique=True)
    op.create_index('idx_16820_ix_assignments_tutor_user_id', 'assignments', ['tutor_user_id'], unique=False)
    op.create_index('idx_16820_ix_assignments_status', 'assignments', ['status'], unique=False)
    op.create_index('idx_16820_ix_assignments_request_id', 'assignments', ['request_id'], unique=False)
    op.alter_column('assignments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('assignments', 'status',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('assignments', 'tutor_user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('assignments', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('assignments', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
